
// Generated by Cadence Encounter(R) RTL Compiler v11.20-s017_1

// Verification Directory fv/priority_encoder 

module priority_encoder(a, b, c, d, y1, y0, v, nand_out);
  input a, b, c, d;
  output y1, y0, v, nand_out;
  wire a, b, c, d;
  wire y1, y0, v, nand_out;
  wire n_0, n_9;
  APRIO1V8_1k4_HV iopad_a(.PAD (a));
  APRIO1V8_1k4_HV iopad_b(.PAD (b));
  APRIO1V8_1k4_HV iopad_c(.PAD (c));
  APRIO1V8_1k4_HV iopad_d(.PAD (d));
  APRIO1V8_1k4_HV iopad_nand_out(.PAD (nand_out));
  APRIO1V8_1k4_HV iopad_v(.PAD (v));
  APRIO1V8_1k4_HV iopad_y0(.PAD (y0));
  APRIO1V8_1k4_HV iopad_y1(.PAD (y1));
  NANDX1_HV nand1(.A (a), .B (b), .Q (nand_out));
  OR3X1_HV g66(.A (n_9), .B (b), .C (a), .Q (v));
  AO21X1_HV g67(.A1 (n_0), .A2 (b), .B1 (d), .Q (y0));
  OR2X2_HV g68(.A (c), .B (d), .Q (n_9));
  INVXL_HV g69(.A (c), .Q (n_0));
  CLKBUFX8_HV g70(.A (n_9), .Q (y1));
endmodule

