
// Generated by Cadence Encounter(R) RTL Compiler v11.20-s017_1

// Verification Directory fv/priority_encoder 

module priority_encoder(a, b, c, d, y1, y0, v, nand_out);
  input a, b, c, d;
  output y1, y0, v, nand_out;
  wire n_0, n_9;
  APRIO1V8_50_HV iopad_a(.Z (a));
  APRIO1V8_50_HV iopad_b(.Z (b));
  APRIO1V8_50_HV iopad_c(.Z (c));
  APRIO1V8_50_HV iopad_d(.Z (d));
  APRIO1V8_50_HV iopad_nand_out(.Z (nand_out));
  APRIO1V8_50_HV iopad_v(.Z (v));
  APRIO1V8_50_HV iopad_y0(.Z (y0));
  APRIO1V8_50_HV iopad_y1(.Z (y1));
  NAND2X4_HV nand1(.A (a), .B (b), .Q (nand_out));
  OR3X1_HV or3(.A (n_9), .B (b), .C (a), .Q (v));
  AO21X1_HV ao2(.A1 (n_0), .A2 (b), .B1 (d), .Q (y0));
  OR2X2_HV or2(.A (c), .B (d), .Q (n_9));
  INVXL_HV invl(.A (c), .Q (n_0));
  CLKBUFX8_HV buffer(.A (n_9), .Q (y1));
  
  APRIO1V8_00_HV vdd_pad(.Z (vdd)) ;
  APRIO1V8_00_HV gnd_pad(.Z (gnd)) ;

endmodule

